### ISSUE TITLE
probleme pour mettre en place l environement

### ISSUE THREAD

**Issue by guillaumebosse** [GendarmerieNationale/ReceptionInfoDrone#4]
voici ce que j'obtiens apres un sudo python main.py

Lancement du script.
Lancement du mode monitor.
Mode monitor de l'interface wlan0mon
Process sniffer:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/ReceptionInfoDrone-master/lib/sniff.py", line 61, in sniffer
    prn=lambda trameBeacon: put_in_queue_beacon(queue_beacon, trameBeacon), count=0, store=False)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 1036, in sniff
    sniffer._run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 907, in _run
    *arg, **karg)] = iface
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 411, in __init__
    set_promisc(self.ins, self.iface)
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 147, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, b"")
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 360, in get_if_index
    return int(struct.unpack("I", get_if(iff, SIOCGIFINDEX)[16:20])[0])
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/common.py", line 31, in get_if
    return ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
IOError: [Errno 19] No such device
Exception IOError: IOError(19, 'No such device') in <bound method L2ListenSocket.__del__ of <scapy.arch.linux.L2ListenSocket object at 0x75639150>> ignored
^C
Arret du script.

cordialement

**Comment by PercyMgn** [comment]
Bonjour,
Comme indiqué dans le stack trace, vous exécutez le code en python 2 —> usr/lib/python2.7
Essayez avec sudo python3 main.py

Si cela résout le problème, merci de close le issue.
Cordialement
